import type { Listing, Review, User, Conversation, Message } from './types';

// Mock current user
export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'alex.chen@ucla.edu',
  verifiedUCLA: true,
  bookmarks: ['listing-1', 'listing-4', 'listing-7'],
};

// Mock listings with UCLA-area addresses
export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Male roommate summer 2026 single',
    price: 1650,
    address: '691 Levering Ave',
    distanceFromCampus: 0.5,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-06-10',
    moveOutDate: '2026-08-10',
    quarter: ['summer'],
    roommatePreference: 'male',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'covered',
      fitnessCenter: true,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Looking for a clean and responsible student to take over my single room for the summer. The apartment is shared with two other chill guys (both juniors). Great natural lighting, comes fully furnished with a desk and chair. All utilities included in the rent price!',
    listerId: 'user-5',
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'listing-2',
    title: 'Cozy studio near campus',
    price: 2200,
    address: '10889 Wilshire Blvd',
    distanceFromCampus: 0.8,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-09-15',
    moveOutDate: '2026-12-15',
    quarter: ['fall'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'garage',
      fitnessCenter: true,
      pool: true,
      hotTub: true,
      accessible: true,
    },
    description: 'Modern studio in a luxury building. Perfect for grad students or upperclassmen. Walking distance to campus with amazing amenities.',
    listerId: 'user-6',
    createdAt: '2026-02-09T14:30:00Z',
  },
  {
    id: 'listing-3',
    title: 'Double room in 2BR apartment',
    price: 950,
    address: '625 Kelton Ave',
    distanceFromCampus: 0.4,
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800',
    ],
    roomType: 'double',
    bathroomType: 'shared',
    moveInDate: '2026-06-20',
    moveOutDate: '2026-09-20',
    quarter: ['summer', 'fall'],
    roommatePreference: 'female',
    verifiedUCLA: true,
    amenities: {
      furnished: false,
      internet: true,
      ac: false,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'street',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Affordable double room perfect for two friends! Close to campus, quiet building, great landlord.',
    listerId: 'user-7',
    createdAt: '2026-02-08T09:15:00Z',
  },
  {
    id: 'listing-4',
    title: 'Large single with private bathroom',
    price: 1850,
    address: '565 Gayley Ave',
    distanceFromCampus: 0.3,
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
      'https://images.unsplash.com/photo-1618219740975-d40978bb7378?w=800',
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-04-01',
    moveOutDate: '2026-06-30',
    quarter: ['spring'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'covered',
      fitnessCenter: true,
      pool: true,
      hotTub: false,
      accessible: false,
    },
    description: 'Spacious single bedroom with ensuite bathroom. Recently renovated with modern finishes. 2-minute walk to campus!',
    listerId: 'user-8',
    createdAt: '2026-02-07T16:45:00Z',
  },
  {
    id: 'listing-5',
    title: 'Summer sublet with amazing roommates',
    price: 1400,
    address: '523 Landfair Ave',
    distanceFromCampus: 0.6,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-06-15',
    moveOutDate: '2026-08-31',
    quarter: ['summer'],
    roommatePreference: 'coed',
    verifiedUCLA: false,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: null,
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Fun summer sublease with 3 awesome roommates who love to cook and hang out! Chill vibe, close to campus.',
    listerId: 'user-9',
    createdAt: '2026-02-06T11:20:00Z',
  },
  {
    id: 'listing-6',
    title: 'Triple room - budget friendly!',
    price: 750,
    address: '10850 Strathmore Dr',
    distanceFromCampus: 1.2,
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
    ],
    roomType: 'triple+',
    bathroomType: 'shared',
    moveInDate: '2026-09-20',
    moveOutDate: '2026-12-20',
    quarter: ['fall'],
    roommatePreference: 'male',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: false,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'street',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Great option for budget-conscious students. Room fits 3 beds comfortably. All roommates are engineering majors.',
    listerId: 'user-10',
    createdAt: '2026-02-05T13:00:00Z',
  },
  {
    id: 'listing-7',
    title: 'Luxury 1BR - short term lease',
    price: 2500,
    address: '10990 Wilshire Blvd',
    distanceFromCampus: 0.9,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800',
      'https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=800',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-07-01',
    moveOutDate: '2026-09-30',
    quarter: ['summer', 'fall'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'garage',
      fitnessCenter: true,
      pool: true,
      hotTub: true,
      accessible: true,
    },
    description: 'High-end 1-bedroom apartment with floor-to-ceiling windows and stunning city views. Perfect for summer internship.',
    listerId: 'user-11',
    createdAt: '2026-02-04T08:30:00Z',
  },
  {
    id: 'listing-8',
    title: 'Female roommate needed - great location',
    price: 1300,
    address: '636 Landfair Ave',
    distanceFromCampus: 0.5,
    images: [
      'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=800',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-01-05',
    moveOutDate: '2026-03-20',
    quarter: ['winter'],
    roommatePreference: 'female',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'street',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Looking for a female roommate for winter quarter. We\'re all bio majors and super friendly!',
    listerId: 'user-12',
    createdAt: '2026-02-03T15:45:00Z',
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    listingId: 'listing-1',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example1',
    sourceName: 'r/ucla',
    text: 'Levering Ave is usually pretty quiet but gets busy during finals. This building has great management and they fix things quickly.',
    timestamp: '2025-12-15T10:00:00Z',
  },
  {
    id: 'review-2',
    listingId: 'listing-1',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/example1',
    sourceName: 'Bruinwalk Apartments',
    text: 'Walking distance to south campus is unbeatable. Units are slightly older but well maintained.',
    timestamp: '2025-08-20T14:30:00Z',
  },
  {
    id: 'review-3',
    listingId: 'listing-4',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example2',
    sourceName: 'r/ucla',
    text: 'Gayley is super close to everything. Literally wake up 10 minutes before class and still make it on time. Parking is tough though.',
    timestamp: '2025-11-05T09:15:00Z',
  },
  {
    id: 'review-4',
    listingId: 'listing-4',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/example2',
    sourceName: 'Bruinwalk Apartments',
    text: 'One of the best locations in Westwood. Building is clean and secure. Would definitely recommend!',
    timestamp: '2025-10-10T16:00:00Z',
  },
  {
    id: 'review-5',
    listingId: 'listing-7',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example3',
    sourceName: 'r/ucla',
    text: 'Wilshire corridor has amazing buildings but they\'re pricey. Worth it if you can afford it - gym and pool are top-notch.',
    timestamp: '2025-09-25T11:30:00Z',
  },
];

// Mock messages and conversations
export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'user-5',
    text: 'Hi! Is the room still available for summer?',
    timestamp: '2026-02-12T09:00:00Z',
    read: true,
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-1',
    text: 'Yes it is! Would you like to schedule a viewing?',
    timestamp: '2026-02-12T09:15:00Z',
    read: true,
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'user-5',
    text: 'That would be great! I\'m free this weekend.',
    timestamp: '2026-02-12T09:20:00Z',
    read: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    listingId: 'listing-1',
    participants: ['user-1', 'user-5'],
    lastMessage: mockMessages[2],
    unreadCount: 1,
  },
];
